stages:
  - build
  - push
build:
  stage: build
  script:
    - echo "$HARBOR_URL/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH$CI_PIPELINE_ID" |  xargs -I {} docker build -t {} .
  only:
    - feature/deployment

Push:
  stage: push 
  script:
      - docker push $HARBOR_URL/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_BRANCH$CI_PIPELINE_ID
  only:
    - feature/deployment 

