apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.teamSlug }}-sl-ingress
{{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
{{- end }}
  tls:
    - hosts:
      - {{ .Values.teamSlug }}.{{ .Values.domainName }}
      secretName: {{ .Values.ingress.secretName }}
  rules:
  - host: {{ .Values.teamSlug }}.{{ .Values.domainName }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.teamSlug }}-sl-dash
            port: 
              number: {{ .Values.dash.service.port }}
      - path: /api/deployments
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.teamSlug }}-sl-deployments
            port: 
              number: {{ .Values.deployments.service.port }}
