apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.teamSlug }}-sl-dash
  labels:
    app.kubernetes.io/name: {{ .Values.teamSlug }}-sl-dash
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.dash.service.type }}
  ports:
    - port: {{ .Values.dash.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.teamSlug }}-sl-dash
    app.kubernetes.io/instance: {{ .Release.Name }}
