apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.teamSlug }}-secrets
#   annotations:
#     "helm.sh/hook": pre-install
  labels:
    app.kubernetes.io/name: {{ .Values.teamSlug }}-sl-dash
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  dbUser: {{ .Values.database.DB_USER | b64enc | quote }}
  dbPass: {{ .Values.database.DB_PASS | b64enc | quote }}
  slApiPrivateKey: {{ .Values.deployments.STACKLABS_API_PRIVATE_KEY | b64enc | quote }}
  softwareZipPrivateToken: {{ .Values.deployments.SOFTWARES_ZIP_PRIVATE_TOKEN | b64enc | quote }}
