apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.teamSlug }}-sl-deployments
  labels:
    app.kubernetes.io/name: {{ .Values.teamSlug }}-sl-deployments
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- with .Values.commonlabels }}
{{ toYaml . | indent 4 }}
{{- end }}

spec:
  replicas: {{ .Values.deployments.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.teamSlug }}-sl-deployments
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.teamSlug }}-sl-deployments
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}-sa
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.deployments.image.repository }}"
          imagePullPolicy: {{ .Values.deployments.image.pullPolicy }}
          env:
          - name: STACKLABS_DEPLOY_DB_HOST
            value: {{ .Values.database.DB_HOST }}
          - name: STACKLABS_DEPLOY_DB_NAME
            value: {{ .Values.teamSlug }}
          - name: STACKLABS_DEPLOY_DB_PORT
            value: {{ .Values.database.DB_PORT | quote}}
          - name: STACKLABS_DEPLOY_DB_USER
            valueFrom:
              secretKeyRef:
                name: {{ .Values.teamSlug }}-secrets
                key: dbUser
          - name: STACKLABS_DEPLOY_DB_PASS
            valueFrom:
              secretKeyRef:
                name: {{ .Values.teamSlug }}-secrets
                key: dbPass
          - name: STACKLABS_API_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.teamSlug }}-secrets
                key: slApiPrivateKey
          - name: SET_MAX_LIMIT_RESOURCE
            value: {{ .Values.deployments.set_max_limit_resource| quote }}
          - name: SOFTWARES_ZIP
            value: {{ .Values.deployments.SOFTWARES_ZIP }}
          - name: SOFTWARES_ZIP_PRIVATE_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ .Values.teamSlug }}-secrets
                key: softwareZipPrivateToken
          - name: ENVIRONMENT
            value: {{ .Values.deployments.ENVIRONMENT }}
          - name: IS_WORKSPACE
            value: "{{ .Values.deployments.IS_WORKSPACE }}"
          - name: KUBERNETES_SERVICE_HOST
            value: {{ .Values.deployments.kubernetesServiceHost | quote }}
          - name: KUBERNETES_SERVICE_PORT
            value: {{ .Values.deployments.kubernetesServicePort | quote }}
          - name: USE_SERVICE_ACCOUNT
            value: {{ .Values.deployments.useServiceAccount | quote }}
        #   - name: KUBE_SERVICE_ACCOUNT_TOKEN
        #     value: {{ .Values.serviceAccountName }}
          - name: NAMESPACE
            value: {{ .Values.deployments.namespace }}
        #   - name: STACKLABS_SERVICE_ACCOUNT_NAME
        #     value: {{ .Values.serviceAccountName }}
          - name: WORKSPACE_KUBE_CLIENT_CERT_DATA
            value: {{ .Values.deployments.WORKSPACE_KUBE_CLIENT_CERT_DATA }}
          - name: WORKSPACE_KUBE_CLIENT_KEY
            value: {{ .Values.deployments.WORKSPACE_KUBE_CLIENT_KEY }}
          - name: CERTIFICATE_AUTHORITY_DATA
            value: {{ .Values.deployments.certificateAuthorityData }}
          - name: STACKLABS_BILLING_ADDRESS
            value: {{ .Values.deployments.stacklabsBillingAddress }}
          - name: STACKLABS_AUTH_ADDRESS
            value: {{ .Values.deployments.stacklabsAuthAddress }}
          ports:
            - name: http
              containerPort: 9302
              protocol: TCP
          resources:
            {{- toYaml .Values.deployments.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
